### ISSUE TITLE
hotend clamp

### ISSUE THREAD

**Issue by m0n5t3r** [zbysniew/Urchin#1]
Stupid question: how is the hotend supposed to be held in place? sorry for bothering you if I'm missing something obvious :-/

**Comment by zbysniew** [comment]
Hi Sabin, with a standard J head design that meets the spec it should be a
force fit into the slot depending in your printer tolerances (I find the
chassis flexes around the J head a bit).

Alternatively if you have one with a grub screw in the nozzle you can
adjust the gap so it is right in the slot or put an Allen key down the
filament hole and wind it out in situ which is much more secure. I'm
currently using this method but it all depends on the grub screw size for
your nozzle.

For Bowden cable you can use a slot mount Bowden mount, there is a file for
this in the repo for use with one touch screw in fittings. Loosely thread
the fitting into the mount, slide it in and tighten in position.

Cheers!

**Comment by m0n5t3r** [comment]
Thanks, so I was missing something (namely, J-head and E3D mounts may look similar, but are slightly different); I'll just shim the one I'm working on right now (because I already made the heatsink with the mount like in the E3D drawings) and make the top flange thicker next time (or go Bowden)

Thanks again.
